title: "Gif Cube"

description: "Turn gifs into physical cubes"

# Build settings
markdown: kramdown

exclude: [
    "documentation",
    "design",
    "node_modules",
    "process_data",
    "server",
    "src",
    "webpack.config.js",
    "package.json",
    "package-lock.json",
    "README.md",
    "tsconfig.json",
    "LICENSE"
]